package com.rl.web.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-10T11:24:07.601+08:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "WsPersonServiceService",
                  wsdlLocation = "http://localhost:8080/cxf_spring_server/service/wsPersonService?wsdl",
                  targetNamespace = "http://wsService.rl.com/")
public class WsPersonServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://wsService.rl.com/", "WsPersonServiceService");
    public final static QName WsPersonServicePort = new QName("http://wsService.rl.com/", "WsPersonServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/cxf_spring_server/service/wsPersonService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsPersonServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/cxf_spring_server/service/wsPersonService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsPersonServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsPersonServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsPersonServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WsPersonServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WsPersonServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WsPersonServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WsPersonService
     */
    @WebEndpoint(name = "WsPersonServicePort")
    public WsPersonService getWsPersonServicePort() {
        return super.getPort(WsPersonServicePort, WsPersonService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsPersonService
     */
    @WebEndpoint(name = "WsPersonServicePort")
    public WsPersonService getWsPersonServicePort(WebServiceFeature... features) {
        return super.getPort(WsPersonServicePort, WsPersonService.class, features);
    }

}
