package com.rl.web.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-10T11:24:07.559+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://wsService.rl.com/", name = "WsPersonService")
@XmlSeeAlso({ObjectFactory.class})
public interface WsPersonService {

    @WebMethod
    @RequestWrapper(localName = "list", targetNamespace = "http://wsService.rl.com/", className = "com.rl.web.stub.List")
    @ResponseWrapper(localName = "listResponse", targetNamespace = "http://wsService.rl.com/", className = "com.rl.web.stub.ListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.rl.web.stub.Person> list();

    @WebMethod
    @RequestWrapper(localName = "addPerson", targetNamespace = "http://wsService.rl.com/", className = "com.rl.web.stub.AddPerson")
    @ResponseWrapper(localName = "addPersonResponse", targetNamespace = "http://wsService.rl.com/", className = "com.rl.web.stub.AddPersonResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String addPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        com.rl.web.stub.Person arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
