package com.chinamobile.cmss.bcse.datastatistics.bean;

public enum RedisDataType {
	ROUGHSORTRULE,
	CAREFULSORTRULE,
	SEARCHANALYSISRULE,
	INTELASSOCIATERULE,
	INDEXRULE,
	SHIELDRULE,
	SEARCHSPREADRULE,
	EPITOMERULE,
	GROUPSTATISTICSRULE,
	INDEXEDFIELDS,
	SHOWNABLEFIELDS,
	APPLICATIONINFO,
	STRINGFIELDS,
	HOTWORD_WEEK,
	HOTWORD_MONTH,
	HOTWORD_DAY
}
