package com.cxf.clazz.web.stup;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-08T14:50:24.009+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://rl.com/", name = "PersonService")
@XmlSeeAlso({ObjectFactory.class})
public interface PersonService {

    @WebMethod
    @RequestWrapper(localName = "get", targetNamespace = "http://rl.com/", className = "com.cxf.clazz.web.stup.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://rl.com/", className = "com.cxf.clazz.web.stup.GetResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String get(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
