server:
  port: 8762
spring:
  application:
    name: eureka-server
eureka:
  client:
    #是否启用湖区注册服务信息，因为这是一个单节点的EurekaServer，不需要同步其他的EurekaServer节点的数据，所以设置为false；
    fetch-registry: true
    #表示是否向eureka注册服务，即在自己的eureka中注册自己，默认为true，此处应该设置为false；
    register-with-eureka: true
    prefer-same-zone-eureka: true
    #地区
    region: suzhou
    availability-zones:
      suzhou: zone-2,zone-1,zone-3
    service-url:
      zone-1: http://peer1:8761/eureka/
      zone-2: http://peer2:8762/eureka/
      zone-3: http://peer3:8763/eureka/
  #    service-url:
  #      defaultZone: http://peer3:8763/eureka/,http://peer2:8762/eureka/
  instance:
    hostname: peer2
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
#  server:
#    #设为false，关闭自我保护，即Eureka server在云心光器件会去统计心跳失败比例在15分钟之内是否低于85%,如果低于85%，EurekaServer
#    #会将这些事例保护起来，让这些事例不会过期，但是在保护器内如果刚哈这个服务提供者非正常下线了，此时服务消费者会拿到一个无效的服务
#    #实例，此时调用会失败，对于这个问题需要服务消费者端有一些容错机制，如重试、断路器等；
#    enable-self-preservation: false
#    #扫描失效服务的间隔时间（单位是毫秒，摩恩是60*1000)，即60s
#    eviction-interval-timer-in-ms: 10000
