'use strict';
var messages= {
  'version': '1.3.0-1',
  'login': '登录',
  'logout': '退出',
	'modify': '修改',
	'delete': '删除',
	'confirm': '确认',
	'userName': '用户名',
	'pwd': '密码',
  'oPwd': '原密码',
	'nPwd': '新密码',
  'verifyPwd': '确认密码',
	'cancel': '取消',
  'reset': '重置',
	'close': '关闭',
	'done': '完成',
  'clear': '清除',
  'save': '保存',
  'submit': '提交',
  'update': '更新',
  'search': '查询',
	'online': '上线',
	'offline': '下线',
  'upload': '上传',
  'edit': '编辑',
  'appName': '应用名称',
  'appDescription': '应用描述',
	'description': '描述',
  'previous': '上一步',
  'next': '下一步',
  'saving': '正在保存',
  'establish': '创建',
  'none': '无',
  'noData': '暂无数据',
  'repetition': '已存在记录',
  'noDescription': '暂无描述',
  'fieldNameTip': '英文字母开头，英文字母、数字或下划线组合，长度不超过30。',
  'error': '网络错误！',
  'noUserList': '用户列表不能为空',
  'noConfigs': function(name) {return '如无'+name+'选项，请在高级配置中进行配置！';},
	'unit': {
		'a': '个'
	},
  'public': {
    'success': '操作成功',
    'fail': '操作失败',
    'error': '抱歉，您没有访问权限或者此页面不存在！',
    'question': '是否删除？',
    'noExist': '记录不存在',
    'noResult': '无结果',
    'empty1': function(name) { return '请填写'+name;},
    'empty2': function(name) {return name+'不能为空';},
    'selectTip': function(name) {return '请选择'+name;},
    'none': function(name) {return '没有可选的'+name;},
  },
  'um': {
    'pwdTextTip': '密码必须由数字、字符、特殊字符三种中的两种组成，密码长度8~16个字符。',
    'pwdEmpty': '请输入密码',
    'pwdError': '密码错误',
    'pwdAsyn': '密码不匹配',
    'pwdUnstrength': '不是强密码',
    'invalidEmail': '邮箱格式错误',
    'pwdSuccess': '修改密码成功',
    'resetSuccess': '重置成功，请查看邮箱'
  },
  'rule': {
    'editRule': '编辑规则',
    'addRule': '添加规则',
    'series': '序号',
    'ruleName': '规则名称',
    'operate': '操作',
    'unfitRuleName': '名称不符合规则',
    'deleteWarning': function(rule) {return rule+'规则不能删除';},
    'editWarning': function(rule) {return rule+'规则不能编辑';},
    'limitation': function(num) {return '配置个数限制为'+num+messages.unit.a;},
    'saveQ': function(rule) {return '是否保存规则'+rule+'？';},
    'repeatField': function(rule) {return '包含字段在规则'+rule+'中已存在！';},
    'repeatWord': function(rule,word) {return '规则rule'+rule+'有重复的关键字'+word;},
    'repeatID': function(rule,id) {return '规则rule'+rule+'有重复的ID'+id;},
    'sameWordWarning': function(rule1,rule2) {return '规则'+rule1+'与'+'规则'+rule2+'有重复的关键字';},
    'repeatRuleName': '规则名称与其他规则名称重复！'
  },
  'segment': {
    'limitLen': function(num) {return '文本长度只支持'+num;}
  },
  'recovery': {
    'dicLoading': '正在加载词典'
  },
  'file': {
    'format': '文件格式不符合要求!',
    'size': '文件大小不在指定范围内!',
    'split': '字段分隔符和多值分隔符不能相同!',
    'none': '还未添加数据文件!',
    'limitation': '上传文件个数超过指定数量!',
    'process': '正在处理文件',
    'processed': '文件处理完成',
    'redo': '请重新上传文件!',
    'select':'请选择文件上传！',
    'tip': '支持不超过1000K的txt文件，建议采用UTF-8无BOM中文编码',
    'tip1': '支持必须含有汉字且不超过1000K的txt文件，建议采用UTF-8无BOM中文编码',
    'tip2': '支持不超过10K的txt文件，建议采用UTF-8无BOM中文编码',
    'fileFormat': function(format) { return '文件支持'+format+'格式上传！'; },
    'fileSizeExceed': function(size) { return '文件大小不超过'+size+'！'; },
    'fileSizeUp': function(size) { return '文件大小需大于'+size+'！'; }
  },
  'create': {
    'uncompletedApp': '存在未完成的应用',
    'appNameTip': '由数字、英文字母或下划线组成，以数字或者英文字母开头，不超过15字符。',
    'importStructTip': '字段之间逗号分隔，',
    'appNameRequired': '应用名称必须填',
    'appNamePattern': '应用名称不符合规则',
    'appNameRepetition': '应用名重名，请修改应用名',
    'drop': '离开此页面将会丢失结构数据',
    'addTable': '请添加数据表',
    'tableEmpty':'表名不能为空！',
    'undefinedField': '表中没有定义字段！',
    'unnamedField': '表中有未命名字段！',
    'noKey': '表中至少选一个字段作为主键',
    'repeat': '字段名不允许为重复字段/特殊字符/数字开头/汉字字段/保留字段，字段名将被移除',
    'fieldReserved': function(name) {return '字段名不允许为'+name+'，请修改！';},
    'fieldExist': function(name) {return '字段名'+name+'已存在！';},
    'tableReserved': function(name) {return '表名不允许为'+name+'请修改！';},
    'tableExist': '您输入的表名已存在，请重新命名！'
  },
  'evaluation': {
    'appExist': '当前应用不存在',
    'appSelect': '请选择当前应用！',
    'configSelect': '请选择粗排配置！',
    'fieldSelect': '请选择解析字段！',
    'nameSelect': '请选择一个标题字段！',
    'formatSelect': '请选择返回格式！',
    'forbidden': '主键字段不可移除！',
    'limitation': '解析字段最多设置2个',
    'unFitField': '主键已默认选中，用户需要选择一个标题字段（如 “name” 字段）'
  }
};
angular
  .module('seApp')
  .factory('Messages', function() {
  	return messages;
  });
